### ISSUE TITLE
Include trimmed adapters in header line

### ISSUE THREAD

**Issue by gringer** [rrwick/Porechop#16]
It would be useful to include the name of the adapters in the header line of FASTA/FASTQ output:

`@2928ef06-e15a-4d9f-9dbe-b7d18e172dbc_t runid=d3311426410a829f91b5484f951a6b26f0f43cc3 read=723 ch=42 start_time=2016-08-04T15:24:56Z [trimmed=Hairpin_2_RC;PCR_1_start]`

I'm currently trying to use Porechop on the [Albertsen Lab](http://albertsenlab.org/can-you-beat-our-nanopore-read-error-correction-we-hope-so/) sequences, and it would be nice to know which (if any) adapters are found in sequences so that I can identify reads that are likely to be high quality.

**Comment by rrwick** [comment]
Thanks for the idea - I'll try to implement this in the next version! Perhaps as an opt-in behaviour you turn on with an option, `--header_note` or something.
