### ISSUE TITLE
Repository not found?

### ISSUE THREAD

**Issue by foamy1881** [rrwick/Porechop#17]
Hi, accessing via linux on terminal Mac OX Sierra and encounter this upon installation? 
fatal repository 'git clone https://github.com/rrwick/Porechop.git' not found?

**Comment by rrwick** [comment]
Sorry, I've got no idea! I've tried that exact command on a couple of different computers, and it works for me. Perhaps it's a Git problem... do you need to configure git to [go through a proxy](https://stackoverflow.com/a/19213999/2438989) or something? Can you clone other repositories from Github other than Porechop?

I don't think this is an issue with Porechop itself, so I'll close this issue now. But go ahead and reopen it if you're still having problems!

Ryan
