### ISSUE TITLE
Trim a fixed number of bases of read ends

### ISSUE THREAD

**Issue by jonhultqvist** [rrwick/Porechop#19]
Thanks for a great tool,

I was wondering if there is a way to trim a fixed number of bases of each read end, even if no adaptor sequence was discovered. Such a flag/feature could be useful when trimming 1D and 1D^2 reads from SQK-LSK308 sequencing runs.

Cheers
Jon

**Comment by wdecoster** [comment]
Although I agree it's easier to have everything in the same tool, the feature you request can be done using [NanoFilt](https://github.com/wdecoster/nanofilt)...

**Comment by jonhultqvist** [comment]
Okey, thank you. I will try that tool instead!
