### ISSUE TITLE
Use pigz for parallel compression

### ISSUE THREAD

**Issue by asl** [rrwick/Porechop#22]
In some cases the gzip compression time clearly dominates the whole running time. The reason is that plain gzip is used. I would suggest checking whether pigz is present, and if yes - then forward ---threads option to pigz to allow much faster parallel compression.

**Comment by rrwick** [comment]
That's a good idea and was a fairly easy one to implement, so I've added it to the current release: v0.2.2. Give it a try!

I'll close this issue now, but let me know if there are any issues and I'll reopen it.
