### ISSUE TITLE
error: [Errno 2] No such file or directory: 'porechop/cpp_functions.so'

### ISSUE THREAD

**Issue by stefanprost** [rrwick/Porechop#23]
Hi,

 I tried to compile several versions of Porechop on my Ubuntu server and always get the same error:

error: [Errno 2] No such file or directory: 'porechop/cpp_functions.so'

Help would be much appreciated!

Cheers,
Stefan

**Comment by rrwick** [comment]
Hi Stefan,

What command gives you that error? I'm wondering if the problem is with the compilation (i.e. cpp_functions.so is never being built) or the installation (i.e. cpp_functions.so isn't being copied to the correct place).

Can you try this installation-free test:
```
git clone https://github.com/rrwick/Porechop.git
cd Porechop
make
./porechop-runner.py -h
```

If that fails, then the compilation is the problem, and could you give me any error messages it prints?

If it succeeds, then I suspect the problem is in the `setup.py` installation. Let me know!

Ryan

**Comment by stefanprost** [comment]
Hi,


 That worked, thanks!


Cheers,

Stefan


________________________________

**Comment by rrwick** [comment]
Glad to hear it!

**Comment by punkrockscience** [comment]
Similar problem here, but the installation-free test doesn't work for me. 
`(porechop) user@test:~/Porechop$ make
g++ -std=c++14 -Iporechop/include -fPIC -O3 -D NDEBUG -Wall -Wextra -pedantic -mtune=native -c -o porechop/src/alignment.o porechop/src/alignment.cpp
g++ -std=c++14 -Iporechop/include -fPIC -O3 -D NDEBUG -Wall -Wextra -pedantic -mtune=native -c -o porechop/src/adapter_align.o porechop/src/adapter_align.cpp
g++ -std=c++14 -Iporechop/include -fPIC -O3 -D NDEBUG -Wall -Wextra -pedantic -mtune=native -shared -Wl,-soname,porechop/cpp_functions.so -o porechop/cpp_functions.so porechop/src/alignment.o porechop/src/adapter_align.o
/usr/bin/ld: /home/user/miniconda3/envs/porechop/bin/../lib/gcc/x86_64-pc-linux-gnu/6.2.0/crtbeginS.o: unrecognized relocation (0x2a) in section `.text'
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
make: *** [porechop/cpp_functions.so] Error 1`
Any insights?

**Comment by rrwick** [comment]
I have never seen this one before! I did a little bit of Googling, and it seems like an issue with libc versions or something. [This comment](https://stackoverflow.com/questions/38388171/cgo-error-unrecognized-relocation-0x2a-in-section-text#comment76934072_38388171) describes a common theme: a mismatch between GCC version and library version.

I see in the error message that it's trying to link against a v6.2.0 library. Could you run `g++ --version` to see if your compiler is also v6.2.0? If not, then I suspect that's your problem.

I'm afraid that I'm not very savvy with C++ compilation stuff, so I'm probably not much more help in troubleshooting. Is this on your computer or a big server? If it's the latter, is there a sys admin who knows the configuration?

My only other thought is that Miniconda might be fiddling with environment variables in some odd way. You could try running `make` outside of Miniconda and see if that works.

Ryan

**Comment by punkrockscience** [comment]
I am using v6.2.0 (in a brand-new conda environment with nothing else in it). 
Thank you for your help! I'll do some googling of my own and update here if I find a solution.

**Comment by punkrockscience** [comment]
Downgrading g++ to 5.2.0 seems to have worked. Thanks again!

**Comment by lab-rat-kid** [comment]
I'm having the same problem, but compiling in g++ 5.2 did not work.
When I try the installation-free test above I get:
```
g++ -std=c++14 -Iporechop/include -fPIC -O3 -D NDEBUG -Wall -Wextra -pedantic -mtune=native -c -o porechop/src/adapter_align.o porechop/src/adapter_align.cpp
cc1plus: error: unrecognized command line option "-std=c++14"
make: *** [porechop/src/adapter_align.o] Error 1
```
