### ISSUE TITLE
DRS read adapters...

### ISSUE THREAD

**Issue by nickschurch** [rrwick/Porechop#27]
Will porechop identify and trim adapters in the Nanopore reads from the new DRS protocol?

**Comment by rrwick** [comment]
Hi Nick,

I suspect not, though I haven't actually tried as I don't have any direct RNA reads to play with. If you have any data share (even just a small number of reads), I might be able to add the adapters in. Let me know!

Ryan

**Comment by phiweger** [comment]
Did you integrate the DRS adapters yet? If not, I could send you some data. Which address should I send it to?

**Comment by rrwick** [comment]
As I just said in issue #40, I added the DRS adapters to Porechop's development branch, but I'm still lacking a test read set, so I'm not sure if they work correctly or not. Hopefully I'll get my hands on one soon, and if it all looks good, I'll move the additions to the master branch and make a new release of Porechop.

**Comment by nickschurch** [comment]
This could be a good test dataset:

https://github.com/nanopore-wgs-consortium/NA12878/blob/master/RNA.md

**Comment by rrwick** [comment]
Thanks for that! I took a good look at it and discussed my results in issue #40. I'll close this issue now because it's essentially the same as #40.

Ryan
