### ISSUE TITLE
After back-transcription, can porechop be used for direct RNA seq kit data?

### ISSUE THREAD

**Issue by phiweger** [rrwick/Porechop#30]
Or might it even work on the raw data?

Thank you,
Adrian

**Comment by rrwick** [comment]
Hi Adrian,

It certainly won't work on the raw data yet, as I haven't included RNA adapter sequences in Porechop.

Does back-transcription mean converting the reads to a complementary DNA sequence _in silico_? If so, Porechop _might_ work, but only if direct RNA uses the same adapter sequences as other kits. If not, the adapters will need to be added to the [adapters.py file](https://github.com/rrwick/Porechop/blob/master/porechop/adapters.py). I can be challenging to actually get the adapter sequences - Nanopore doesn't always publish them (or publish them in their entirety).

Ryan

**Comment by rrwick** [comment]
Closing now because direct RNA reads are discussed in issues #27 and #40.
