### ISSUE TITLE
1d^2 adapter basecalls

### ISSUE THREAD

**Issue by joshquick** [rrwick/Porechop#35]
```
# But when looking at actual reads, I found two parts. The first corresponds to one end
# of the provided sequences (through slightly different):
```

Was talking to John Tyson about this and he pointed out that the 1d^2 adapter contains a chemical modification which is what gives it affinity to the R9.5 pore so it looks like it is throwing the basecalling off here as you observe the reads don't match the documentation. As it is quite a long adapter it probably doesn't matter but just wanted to point it out.

**Comment by rrwick** [comment]
That's good to know - thanks for the info!

Perhaps if the modification is in the middle of the adapter, that would explain why I tend to see the start and the end but not always the middle.
