### ISSUE TITLE
Porechop on windows 

### ISSUE THREAD

**Issue by kanchanhole** [rrwick/Porechop#52]
Hello,

I could install porechopp on windows using bioconda

**Comment by wdecoster** [comment]
This doesn't look like a question, is it?

**Comment by kanchanhole** [comment]
I read in the Readme that if someone is able to install this on windows they should report. Apologies if this wasn't the best way to convey.

**Comment by wdecoster** [comment]
Oh my apologies, I wasn't aware of that :)

**Comment by kanchanhole** [comment]
no worries

**Comment by CrMallard** [comment]
What windows version were you using? I'm trying to install it with bioconda on windows 7 and only get the 'porechop not found in existing channels' error when running `conda install porechop`
