### ISSUE TITLE
Missing porechop/cpp_functions.so

### ISSUE THREAD

**Issue by iosefward** [rrwick/Porechop#58]
Installing as described in the readme, but it's throwing the error:

error: [Errno 2] No such file or directory: 'porechop/cpp_functions.so'

Missing intentionally and not removed from the code, or missing accidentally?

**Comment by iosefward** [comment]
Belay that, my bad. I was missing some arcane trickery with gcc compilers on the machine.

**Comment by lab-rat-kid** [comment]
what fixed this?
